# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Email 

on:
  schedule:
   - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  render:
    runs-on: ubunto-latest
    env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
    steps:  
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/423179119965/locations/global/workloadIdentityPools/github-email/subject/SUBJECT_ATTRIBUTE_VALUE"
          service_account: "iotree-email-test@just-genius-337505.iam.gserviceaccount.com"
      - name: Install dependencies
        run: |
          install.packages("blastula", type = "win.binary")
          install.packages("rmarkdown")
        shell: Rscript {0}
      - name: Script
        run: Rscript email_test_script.R
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add output/*
          git commit -am "commit on $(date)"
          git push origin main
        
    
